const iconMapping = {
    'Museum': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Museum.png',
    'Geyser': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Geyser.png',
    'Amphitheater': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Amphitheater.png',
    'Peak': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Peak.png',
    'Waterfall': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Waterfall.png',
    'Information': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Information.png',
    'Visitor Center': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Information.png',
    'Store': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Store.png',
    'Picnic Area': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Picnic.png',
    'Food Service': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Food%20Service.png',
    'Lodging': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Lodging.png',
    'Campground': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Camping.png',
    'Campsite': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Camping.png',
    'RV Campground': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/RV%20Campground.png',
    'Dump Station': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Dumpstation.png',
    'Parking Lot': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Parking.png',
    'Entrance Station': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Entrance%20Station.png',
    'Trailhead': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Trailhead.png',
    'Post Office': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Post%20Office.png',
    'Ranger Station': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Ranger%20Station.png',
    'Restroom': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Restroom.png',
  };
  