const iconMapping = {
    'Museum': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Museum.png',
    'Geyser': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Geyser.png',
    'Amphitheater': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Amphitheater.png',
    'Peak': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Peak.png',
    'Waterfall': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Waterfall.png',
    'Information': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Information.png',
    'Visitor Center': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Information.png',
    'Store': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Store.png',
    'Picnic Area': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Picnic.png',
    'Food Service': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Food%20Service.png',
    'Lodging': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Lodging.png',
    'Campground': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Camping.png',
    'Campsite': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Camping.png',
    'Primitve Camping': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Camping.png',
    'RV Campground': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/RV%20Campground.png',
    'Dump Station': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Dumpstation.png',
    'Parking Lot': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Parking.png',
    'Entrance Station': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Entrance%20Station.png',
    'Trailhead': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Trailhead.png',
    'Post Office': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Post%20Office.png',
    'Ranger Station': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Ranger%20Station.png',
    'Headquarters': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Ranger%20Station.png',
    'Restroom': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Restroom.png',
    'Airport': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Airport.png',
    'Airstrip': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Airport.png',
    'Barn': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Barn.png',
    'Boat Launch': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Boat%20Launch.png',
    'Bridge': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Bridge.png',
    'Bus Stop': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Busstop.png',
    'Cemetery': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Cemetery.png',
    'Chapel': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Chapel.png',
    'Fire Station': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Fire%20Station.png',
    'Gas Station': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Gas%20Station.png',
    'Point Of Interest': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/POI.png',
    'Populated Place': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/POI.png',
    'Historic Site': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/POI.png',
    'Interpretive Exhibit': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/POI.png',
    'Building': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/POI.png',
    'Arch': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/POI.png',
    'Historic Building': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/POI.png',
    'Lake': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Lake.png',
    'Monument': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Monument.png',
    'Potable Water': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Potable%20Water.png',
    'Shelter': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Shelter.png',
    'Shower': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Shower.png',
    'Stable': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Stable.png',
    'Telephone': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Telephone.png',
    'Train Station': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Trainstation.png',
    'Tunnel': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Tunnel.png',
    'Viewpoint': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/Viewpoint.png',
    'First Aid Station': 'https://raw.githubusercontent.com/VnssHks/BlazingTheTrail/main/Icons/First%20Aid%20Station.png',
  };
  